// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQDxD9tkyRvn41Tf0XH9YbA-1q3r_uvI',
    appId: '1:521129122970:web:0b1e23815830b9fd3a9323',
    messagingSenderId: '521129122970',
    projectId: 'musings-2904',
    authDomain: 'musings-2904.firebaseapp.com',
    storageBucket: 'musings-2904.firebasestorage.app',
    measurementId: 'G-TY6ZZSPZJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfiQREdSzwmUOE1fX-XFJryS9VfmuMaFM',
    appId: '1:521129122970:android:1499ceabf0b94e363a9323',
    messagingSenderId: '521129122970',
    projectId: 'musings-2904',
    storageBucket: 'musings-2904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkVih92o0Cj_xdhYGXiGEkLgQqM-oagM',
    appId: '1:521129122970:ios:87786dbdb50fc76f3a9323',
    messagingSenderId: '521129122970',
    projectId: 'musings-2904',
    storageBucket: 'musings-2904.firebasestorage.app',
    iosBundleId: 'com.example.musings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkVih92o0Cj_xdhYGXiGEkLgQqM-oagM',
    appId: '1:521129122970:ios:87786dbdb50fc76f3a9323',
    messagingSenderId: '521129122970',
    projectId: 'musings-2904',
    storageBucket: 'musings-2904.firebasestorage.app',
    iosBundleId: 'com.example.musings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIQDxD9tkyRvn41Tf0XH9YbA-1q3r_uvI',
    appId: '1:521129122970:web:6aec8340187d2f8b3a9323',
    messagingSenderId: '521129122970',
    projectId: 'musings-2904',
    authDomain: 'musings-2904.firebaseapp.com',
    storageBucket: 'musings-2904.firebasestorage.app',
    measurementId: 'G-L9RD0XFVFX',
  );
}
